# Generated by Django 4.0.6 on 2022-08-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dollshop1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price_and_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
