# Generated by Django 4.0.6 on 2022-07-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dollshop1', '0002_alter_commentary_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dollshop1.product', verbose_name='Товар'),
        ),
    ]
